services:
  - type: web
    name: chatbot2024      # El nombre del servicio
    runtime: node          # El entorno de ejecución (Node.js en este caso)
    plan: free             # El plan de despliegue
    buildCommand: yarn build
    startCommand: yarn start
    branch: main
